"""empty message

Revision ID: 291880d88df3
Revises: 9daaea18e19c
Create Date: 2023-05-07 18:10:35.276917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291880d88df3'
down_revision = '9daaea18e19c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    op.create_table(
        'shows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('show_date', sa.DateTime(), nullable=False),
        # Define other columns here
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('show_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
