"""empty message

Revision ID: 2f96b86a36a0
Revises: 53032f3d9413
Create Date: 2023-05-07 14:25:32.715089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f96b86a36a0'
down_revision = '53032f3d9413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('looking_Venues',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=5),
               existing_nullable=True)

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_Venues', sa.String(length=5), nullable=True))
        batch_op.drop_column('looking_talen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_talen', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('looking_Venues')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('looking_Venues',
               existing_type=sa.String(length=5),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
