"""empty message

Revision ID: 676c00a6d4f4
Revises: e1ef2b5e00a5
Create Date: 2023-05-07 20:45:15.996899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676c00a6d4f4'
down_revision = 'e1ef2b5e00a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.String(length=5), nullable=True))
        batch_op.drop_column('looking_Venues')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_Venues', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###
