"""empty message

Revision ID: 9daaea18e19c
Revises: 2f96b86a36a0
Create Date: 2023-05-07 15:04:07.147017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9daaea18e19c'
down_revision = '2f96b86a36a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=True))
        batch_op.drop_column('looking_Venues')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_Venues', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###
